ensure:
    @mkdir -p .vscode
    cp -f ${REPO_ROOT}/source/common/.vscode/settings.json .vscode/settings.json
    @cd ${REPO_ROOT}/source/assets && just build

build: ensure
    cargo build --release

dev: ensure
    cargo run --release

run: ensure lint
    cargo run --release

test:

lint: build
    cargo clippy --fix --allow-dirty --allow-staged

clean:

